- name: Configure webserver
  hosts: wordpress
  gather_facts: True
  tasks:
    - name: install apache
      become: yes
      ansible.builtin.import_tasks: packages/apache.yml
      tags: [install-apache]
    - name: install php-extensions
      become: yes
      ansible.builtin.import_tasks: packages/php-extensions.yml
      tags: [install-php-extensions]